// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function reduceAndSort(tags) {
  return tags.filter((function (item, index) {
                  return tags.indexOf(item) === index;
                })).sort();
}

export {
  reduceAndSort ,
  
}
/* No side effect */
