// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as App from "./App.js";
import * as React from "react";
import * as ReactDOMRe from "../../../node_modules/reason-react/lib/es6_global/src/ReactDOMRe.js";

ReactDOMRe.renderToElementWithId(React.createElement("div", undefined, React.createElement(App.make, { })), "root");

export {
  
}
/*  Not a pure module */
