// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function Tags(Props) {
  var tags = Props.tags;
  console.log(tags);
  return React.createElement("div", undefined, "tags");
}

var make = Tags;

export {
  make ,
  
}
/* react Not a pure module */
